version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "homeassistant"
    groups:
      testing:
        patterns:
          - "pytest*"
          - "homeassistant-stubs"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
