name: Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade mypy
        run: |
          python -m pip install --upgrade pip
          pip install "mypy>=1.10"
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          use-pylint: false
          use-pycodestyle: true
          use-flake8: true
          use-black: true
          use-mypy: true
          use-isort: true
          extra-pylint-options: ""
          extra-pycodestyle-options: "--ignore=E501,W503,E203"
          extra-flake8-options: "--ignore=E501,W503,E203"
          extra-black-options: ""
          # Whilst gli4py is not statically typed we must ignore it
          extra-mypy-options: "--ignore-missing-imports -V"
          extra-isort-options: "--multi-line 3 --trailing-comma"
