name: Linting

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  linting:
    name: Pre-commit & Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Prepare and install deps
        uses: ./.github/actions/install-deps

      - uses: actions/cache@v4
        name: Cache pre-commit hooks
        with:
          path: ~/.cache/pre-commit/
          key: >
            ${{ format('pre-commit-{0}-{1}-{2}',
            runner.os,
            env.PYTHON_VERSION,
            hashFiles('.pre-commit-config.yaml')
            ) }}
          restore-keys: |
            pre-commit-${{ runner.os }}-${{ env.PYTHON_VERSION }}-
            pre-commit-${{ runner.os }}-

      - name: Run pre-commit on all files
        run: |
          uv run pre-commit run --all-files --show-diff-on-failure --color=always
