name: Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            mypy-dev==1.17.0a2 \
            black \
            isort \
            flake8 \
            pycodestyle \
            pydantic

      - name: Run black
        run: |
          black --check .
      - name: Run isort
        run: |
          isort --multi-line 3 --trailing-comma . -c --diff
      - name: Run flake8
        run: |
          flake8 --ignore=E501,W503,E203 .
      - name: Run pycodestyle
        run: |
          pycodestyle --ignore=E501,W503,E203 .
      - name: Run mypy
        run: |
          mypy --ignore-missing-imports --show-error-codes .