name: Pylint

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Prepare and install deps
        uses: ./.github/actions/install-deps

      - name: Analysing the code with pylint
        run: |
          uv run pylint custom_components/glinet
